### ISSUE TITLE
P2B2 tf/keras API

### ISSUE THREAD

**Issue by rajeeja** [ECP-CANDLE/Benchmarks#92]
`Traceback (most recent call last):
  File "p2b1_baseline_keras2.py", line 298, in <module>
    main()
  File "p2b1_baseline_keras2.py", line 294, in main
    run(gParameters)
  File "p2b1_baseline_keras2.py", line 231, in run
    molecular_model.compile(optimizer=opt, loss=loss_func, metrics=['mean_squared_error', 'mean_absolute_error'])
  File "/nfs/gce/software/custom/linux-ubuntu18.04-x86_64/anaconda3/rolling/envs/candle-tf1/lib/python3.7/site-packages/keras/engine/training.py", line 95, in compile
    self.optimizer = optimizers.get(optimizer)
  File "/nfs/gce/software/custom/linux-ubuntu18.04-x86_64/anaconda3/rolling/envs/candle-tf1/lib/python3.7/site-packages/keras/optimizers.py", line 873, in get
    str(identifier))
ValueError: Could not interpret optimizer identifier: <tensorflow.python.keras.optimizer_v2.adam.Adam object at 0x7f06fa323d90>
`

This might be due to mixed Tensorflow keras and keras API in the code.

**Comment by rajeeja** [comment]
https://stackoverflow.com/questions/50056356/could-not-interpret-optimizer-identifier-error-in-keras

**Comment by jmohdyusof** [comment]
All the imports should be tensorflow.keras in the candle library and in the code. Have you looked at the p2b1 imports?
